# Generated by Django 5.0.6 on 2024-06-10 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('identity_card', models.CharField(max_length=18)),
                ('amount', models.FloatField()),
                ('application_data', models.DateTimeField(auto_now_add=True)),
                ('loan_duration', models.IntegerField()),
                ('status', models.CharField(max_length=100, null=True)),
                ('remark', models.TextField(default='This is remark about the loan application')),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='common.account')),
            ],
            options={
                'verbose_name': 'loan application',
                'db_table': 'loan_application',
            },
        ),
        migrations.CreateModel(
            name='LoanDepartmentManager',
            fields=[
                ('loan_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1024)),
                ('other_information', models.TextField(default='This is additional information from the loan department manager')),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='common.employee')),
            ],
            options={
                'verbose_name': 'loan department manager',
                'db_table': 'loan_department_manager',
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('lender_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.BooleanField()),
                ('lender_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(null=True)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='loan.loanapplication')),
                ('loan_manager_id', models.ForeignKey(db_column='loan_manager_id', on_delete=django.db.models.deletion.CASCADE, to='loan.loandepartmentmanager')),
            ],
            options={
                'db_table': 'lender',
            },
        ),
        migrations.CreateModel(
            name='LoanExaminer',
            fields=[
                ('loan_examiner_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1024)),
                ('other_information', models.TextField(default='This is additional information from the loan examiner')),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='common.employee')),
            ],
            options={
                'verbose_name': 'loan examiner',
                'db_table': 'loan_examiner',
            },
        ),
        migrations.CreateModel(
            name='LoanApproval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.BooleanField()),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(null=True)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='loan.loanapplication')),
                ('loan_examiner_id', models.ForeignKey(db_column='loan_examiner_id', on_delete=django.db.models.deletion.CASCADE, to='loan.loanexaminer')),
            ],
            options={
                'verbose_name': 'loan approval',
                'db_table': 'loan_approval',
            },
        ),
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('is_repay', models.BooleanField(default=False)),
                ('remark', models.TextField(null=True)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='loan.loanapplication')),
                ('loan_examiner_id', models.ForeignKey(db_column='loan_examiner_id', on_delete=django.db.models.deletion.CASCADE, to='loan.loanexaminer')),
                ('loan_manager_id', models.ForeignKey(db_column='loan_manager_id', on_delete=django.db.models.deletion.CASCADE, to='loan.loandepartmentmanager')),
            ],
            options={
                'verbose_name': 'loan record',
                'db_table': 'loan_record',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('repayment_id', models.AutoField(primary_key=True, serialize=False)),
                ('repayment_date', models.DateTimeField(auto_now_add=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('remark', models.TextField(null=True)),
                ('loan_id', models.ForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.CASCADE, to='loan.loanrecord')),
            ],
            options={
                'verbose_name': 'loan repayment',
                'db_table': 'loan_repayment',
            },
        ),
    ]
