# Generated by Django 5.0.6 on 2024-06-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplication',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='loanapproval',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='loanrecord',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='loanapproval',
            name='loan_examiner_id',
        ),
        migrations.RemoveField(
            model_name='loandepartmentmanager',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='loanrecord',
            name='loan_manager_id',
        ),
        migrations.RemoveField(
            model_name='loanexaminer',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='loanrecord',
            name='loan_examiner_id',
        ),
        migrations.RemoveField(
            model_name='loanrepayment',
            name='loan_id',
        ),
        migrations.DeleteModel(
            name='Lender',
        ),
        migrations.DeleteModel(
            name='LoanApplication',
        ),
        migrations.DeleteModel(
            name='LoanApproval',
        ),
        migrations.DeleteModel(
            name='LoanDepartmentManager',
        ),
        migrations.DeleteModel(
            name='LoanExaminer',
        ),
        migrations.DeleteModel(
            name='LoanRecord',
        ),
        migrations.DeleteModel(
            name='LoanRepayment',
        ),
    ]
