# Generated by Django 5.0.6 on 2024-06-12 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0009_alter_account_identity_card"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="blacklist",
            name="online_bank_manager_id",
        ),
        migrations.RemoveField(
            model_name="blacklist",
            name="user_id",
        ),
        migrations.RemoveField(
            model_name="cashier",
            name="employee",
        ),
        migrations.DeleteModel(
            name="deposit_record",
        ),
        migrations.RemoveField(
            model_name="online_bank_manager",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="sys_manage",
            name="employee",
        ),
        migrations.DeleteModel(
            name="transfer_record",
        ),
        migrations.DeleteModel(
            name="withdrawal_record",
        ),
        migrations.DeleteModel(
            name="account",
        ),
        migrations.DeleteModel(
            name="BlackList",
        ),
        migrations.DeleteModel(
            name="online_user",
        ),
        migrations.DeleteModel(
            name="cashier",
        ),
        migrations.DeleteModel(
            name="online_bank_manager",
        ),
        migrations.DeleteModel(
            name="employee",
        ),
        migrations.DeleteModel(
            name="sys_manage",
        ),
    ]
