# Generated by Django 5.0.4 on 2024-06-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counteropt', '0001_initial'),
        ('creditcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardexaminer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counteropt.employee'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='online_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='counteropt.online_user'),
        ),
        migrations.AlterField(
            model_name='creditcardapplication',
            name='online_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counteropt.online_user'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Online_user',
        ),
    ]
