# Generated by Django 5.0.4 on 2024-06-08 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcard', '0002_alter_creditcardexaminer_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(default='name', max_length=20)),
                ('identity_card', models.CharField(default='000000000000000000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Online_user',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('identity_card', models.CharField(default='000000000000000000', max_length=18)),
            ],
        ),
        migrations.AlterField(
            model_name='creditcardexaminer',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditcard.employee'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='online_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='creditcard.online_user'),
        ),
        migrations.AlterField(
            model_name='creditcardapplication',
            name='online_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditcard.online_user'),
        ),
    ]
