# Generated by Django 5.0.6 on 2024-06-07 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('counteropt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=80, unique=True)),
                ('latest_exchange_buying_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('latest_exchange_selling_rate', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ForeignExchangeOperator',
            fields=[
                ('foreign_exchange_operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('alter_name_authority', models.BooleanField(default=False)),
                ('alter_rate_authority', models.BooleanField(default=False)),
                ('add_authority', models.BooleanField(default=False)),
                ('delete_authority', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counteropt.employee')),
            ],
            options={
                'db_table': 'foreign_exchange_operator',
                'ordering': ['foreign_exchange_operator_id'],
            },
        ),
        migrations.CreateModel(
            name='ForeignExchangeTrading',
            fields=[
                ('foreign_exchange_trading_id', models.AutoField(primary_key=True, serialize=False)),
                ('buy_or_sell', models.BooleanField(default=False)),
                ('rmb_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('currency_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('trading_datetime', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counteropt.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreign_exchange.currency')),
                ('online_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counteropt.online_user')),
            ],
        ),
        migrations.CreateModel(
            name='RateUpdateRecord',
            fields=[
                ('rate_update_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('buying_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('selling_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('update_datetime', models.DateTimeField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreign_exchange.currency')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyHolding',
            fields=[
                ('currency_holding_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foreign_exchange.currency')),
                ('online_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counteropt.online_user')),
            ],
            options={
                'unique_together': {('currency', 'online_user')},
            },
        ),
    ]
