# Generated by Django 5.0.6 on 2024-06-08 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('foreign_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyholding',
            name='online_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.online_user'),
        ),
        migrations.AlterField(
            model_name='foreignexchangeoperator',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.employee'),
        ),
        migrations.AlterField(
            model_name='foreignexchangetrading',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.account'),
        ),
        migrations.AlterField(
            model_name='foreignexchangetrading',
            name='online_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.online_user'),
        ),
    ]
