# Generated by Django 5.0.6 on 2024-06-10 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('card_type', models.IntegerField()),
                ('balance', models.FloatField(default=0.0)),
                ('current_deposit', models.FloatField(default=0.0)),
                ('uncredited_deposit', models.FloatField(default=0.0)),
                ('credit_limit', models.FloatField(default=10000)),
                ('lent_money', models.FloatField(null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=80, unique=True)),
                ('latest_exchange_buying_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('latest_exchange_selling_rate', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='deposit_record',
            fields=[
                ('deposit_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('deposit_type', models.CharField(max_length=10)),
                ('auto_renew_status', models.BooleanField(null=True)),
                ('deposit_start_date', models.DateField()),
                ('deposit_update_date', models.DateField()),
                ('deposit_end_date', models.DateField(null=True)),
                ('deposit_amount', models.FloatField()),
                ('cashier_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(default='Unknown', max_length=20)),
                ('identity_card', models.CharField(default='Unknown', max_length=18)),
                ('employee_sex', models.IntegerField(default=0)),
                ('phone_number', models.CharField(default='Unknown', max_length=20)),
                ('occupation_name', models.CharField(default='Unknown', max_length=50)),
                ('is_employeed', models.BooleanField(default='False')),
                ('other_information', models.CharField(default='Unknown', max_length=1021)),
            ],
        ),
        migrations.CreateModel(
            name='online_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('identity_card', models.CharField(max_length=18)),
                ('annual_income', models.FloatField(null=True)),
                ('property_valuation', models.FloatField(null=True)),
                ('service_year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_record',
            fields=[
                ('transfer_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_in_id', models.IntegerField()),
                ('account_out_id', models.IntegerField()),
                ('transfer_date', models.DateField()),
                ('transfer_amount', models.FloatField()),
                ('cashier_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='withdrawal_record',
            fields=[
                ('withdrawal_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('withdrawal_date', models.DateField()),
                ('withdrawal_amount', models.FloatField()),
                ('cashier_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cashier',
            fields=[
                ('cashier_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('trade_authority', models.BooleanField()),
                ('manage_authority', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignExchangeOperator',
            fields=[
                ('foreign_exchange_operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('alter_name_authority', models.BooleanField(default=False)),
                ('alter_rate_authority', models.BooleanField(default=False)),
                ('add_authority', models.BooleanField(default=False)),
                ('delete_authority', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.employee')),
            ],
            options={
                'db_table': 'foreign_exchange_operator',
                'ordering': ['foreign_exchange_operator_id'],
            },
        ),
        migrations.CreateModel(
            name='ForeignExchangeTrading',
            fields=[
                ('foreign_exchange_trading_id', models.AutoField(primary_key=True, serialize=False)),
                ('buy_or_sell', models.BooleanField(default=False)),
                ('rmb_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('currency_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('trading_datetime', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.currency')),
                ('online_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.online_user')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='identity_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.online_user'),
        ),
        migrations.CreateModel(
            name='RateUpdateRecord',
            fields=[
                ('rate_update_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('buying_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('selling_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('update_datetime', models.DateTimeField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.currency')),
            ],
        ),
        migrations.CreateModel(
            name='sys_manager',
            fields=[
                ('sys_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyHolding',
            fields=[
                ('currency_holding_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.currency')),
                ('online_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.online_user')),
            ],
            options={
                'unique_together': {('currency', 'online_user')},
            },
        ),
    ]
