# Generated by Django 5.0.6 on 2024-06-13 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('identity_card', models.CharField(max_length=18)),
                ('phone_num', models.CharField(default='10086', max_length=20)),
                ('card_type', models.IntegerField()),
                ('balance', models.FloatField(default=0.0)),
                ('current_deposit', models.FloatField(default=0.0)),
                ('uncredited_deposit', models.FloatField(default=0.0)),
                ('credit_limit', models.FloatField(default=10000)),
                ('lent_money', models.FloatField(null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('uncredited_deposit_update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=80, unique=True)),
                ('latest_exchange_buying_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('latest_exchange_selling_rate', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='deposit_record',
            fields=[
                ('deposit_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('deposit_type', models.CharField(max_length=10)),
                ('auto_renew_status', models.BooleanField(null=True)),
                ('deposit_start_date', models.DateField()),
                ('deposit_update_date', models.DateField()),
                ('deposit_end_date', models.DateField(null=True)),
                ('deposit_amount', models.FloatField()),
                ('cashier_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(default='Unknown', max_length=20)),
                ('identity_card', models.CharField(default='Unknown', max_length=18)),
                ('employee_sex', models.IntegerField(default=0)),
                ('phone_number', models.CharField(default='Unknown', max_length=20)),
                ('occupation_name', models.CharField(default='Unknown', max_length=50)),
                ('is_employeed', models.BooleanField(default='False')),
                ('other_information', models.CharField(default='Unknown', max_length=1021)),
            ],
        ),
        migrations.CreateModel(
            name='online_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='Unknown', max_length=20)),
                ('password', models.CharField(default='666666', max_length=20)),
                ('identity_card', models.CharField(max_length=18, unique=True)),
                ('phone_num', models.CharField(default='10086', max_length=20)),
                ('annual_income', models.FloatField(null=True)),
                ('property_valuation', models.FloatField(null=True)),
                ('service_year', models.IntegerField(null=True)),
                ('is_frozen', models.BooleanField(default=False)),
                ('is_lost', models.BooleanField(default=False)),
                ('is_blacklisted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='transfer_record',
            fields=[
                ('transfer_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_in_id', models.IntegerField()),
                ('account_out_id', models.IntegerField()),
                ('transfer_date', models.DateField()),
                ('transfer_amount', models.FloatField()),
                ('cashier_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='withdrawal_record',
            fields=[
                ('withdrawal_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.IntegerField()),
                ('withdrawal_date', models.DateField()),
                ('withdrawal_amount', models.FloatField()),
                ('cashier_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardExaminer',
            fields=[
                ('credit_examiner_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_authority', models.BooleanField(default=False)),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='cashier',
            fields=[
                ('cashier_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('trade_authority', models.BooleanField()),
                ('manage_authority', models.BooleanField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignExchangeOperator',
            fields=[
                ('foreign_exchange_operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('alter_name_authority', models.BooleanField(default=False)),
                ('alter_rate_authority', models.BooleanField(default=False)),
                ('add_authority', models.BooleanField(default=False)),
                ('delete_authority', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.employee')),
            ],
            options={
                'db_table': 'foreign_exchange_operator',
                'ordering': ['foreign_exchange_operator_id'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('identity_card', models.CharField(max_length=18)),
                ('amount', models.FloatField()),
                ('application_data', models.DateTimeField(auto_now_add=True)),
                ('loan_duration', models.IntegerField()),
                ('status', models.CharField(max_length=100, null=True)),
                ('remark', models.TextField(default='This is remark about the loan application')),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='common.account')),
            ],
            options={
                'verbose_name': 'loan application',
                'db_table': 'loan_application',
            },
        ),
        migrations.CreateModel(
            name='LoanDepartmentManager',
            fields=[
                ('loan_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1024)),
                ('other_information', models.TextField(default='This is additional information from the loan department manager')),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='common.employee')),
            ],
            options={
                'verbose_name': 'loan department manager',
                'db_table': 'loan_department_manager',
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('lender_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.BooleanField()),
                ('lender_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(null=True)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='common.loanapplication')),
                ('loan_manager_id', models.ForeignKey(db_column='loan_manager_id', on_delete=django.db.models.deletion.CASCADE, to='common.loandepartmentmanager')),
            ],
            options={
                'db_table': 'lender',
            },
        ),
        migrations.CreateModel(
            name='LoanExaminer',
            fields=[
                ('loan_examiner_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=1024)),
                ('other_information', models.TextField(default='This is additional information from the loan examiner')),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='common.employee')),
            ],
            options={
                'verbose_name': 'loan examiner',
                'db_table': 'loan_examiner',
            },
        ),
        migrations.CreateModel(
            name='LoanApproval',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.BooleanField()),
                ('approval_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(null=True)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='common.loanapplication')),
                ('loan_examiner_id', models.ForeignKey(db_column='loan_examiner_id', on_delete=django.db.models.deletion.CASCADE, to='common.loanexaminer')),
            ],
            options={
                'verbose_name': 'loan approval',
                'db_table': 'loan_approval',
            },
        ),
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('effective_date', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('is_repay', models.BooleanField(default=False)),
                ('is_overdue', models.BooleanField(default=False)),
                ('remark', models.TextField(null=True)),
                ('application_id', models.ForeignKey(db_column='application_id', on_delete=django.db.models.deletion.CASCADE, to='common.loanapplication')),
                ('loan_examiner_id', models.ForeignKey(db_column='loan_examiner_id', on_delete=django.db.models.deletion.CASCADE, to='common.loanexaminer')),
                ('loan_manager_id', models.ForeignKey(db_column='loan_manager_id', on_delete=django.db.models.deletion.CASCADE, to='common.loandepartmentmanager')),
            ],
            options={
                'verbose_name': 'loan record',
                'db_table': 'loan_record',
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('repayment_id', models.AutoField(primary_key=True, serialize=False)),
                ('repayment_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.TextField(null=True)),
                ('loan_id', models.ForeignKey(db_column='loan_id', on_delete=django.db.models.deletion.CASCADE, to='common.loanrecord')),
            ],
            options={
                'verbose_name': 'loan repayment',
                'db_table': 'loan_repayment',
            },
        ),
        migrations.CreateModel(
            name='online_bank_manager',
            fields=[
                ('online_bank_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignExchangeTrading',
            fields=[
                ('foreign_exchange_trading_id', models.AutoField(primary_key=True, serialize=False)),
                ('buy_or_sell', models.BooleanField(default=False)),
                ('rmb_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('currency_amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('trading_datetime', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.currency')),
                ('online_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.online_user')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardApplication',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('apply_status', models.BooleanField(default=False)),
                ('apply_result', models.BooleanField(default=False)),
                ('apply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('have_open', models.BooleanField(default=False)),
                ('creditCardExaminer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.creditcardexaminer')),
                ('online_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.online_user')),
            ],
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('online_bank_manager_id', models.ForeignKey(db_column='online_bank_manager_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='common.online_bank_manager')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='common.online_user')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='common.online_user'),
        ),
        migrations.CreateModel(
            name='RateUpdateRecord',
            fields=[
                ('rate_update_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('buying_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('selling_rate', models.DecimalField(decimal_places=5, max_digits=10)),
                ('update_datetime', models.DateTimeField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.currency')),
            ],
        ),
        migrations.CreateModel(
            name='sys_manager',
            fields=[
                ('sys_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyHolding',
            fields=[
                ('currency_holding_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.currency')),
                ('online_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.online_user')),
            ],
            options={
                'unique_together': {('currency', 'online_user')},
            },
        ),
    ]
