# Generated by Django 5.0.6 on 2024-06-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="online_user",
            name="user_name",
            field=models.CharField(default="Unknown", max_length=20, unique=True),
        ),
    ]
