# Generated by Django 5.0.6 on 2024-06-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='open_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='uncredited_deposit_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
