# Generated by Django 5.0.6 on 2024-06-13 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_account_open_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='open_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='account',
            name='uncredited_deposit_update_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
