# Generated by Django 5.0.6 on 2024-06-12 07:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_account_open_date_creditcardexaminer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="phone_num",
            field=models.CharField(default="10086", max_length=20),
        ),
        migrations.AddField(
            model_name="account",
            name="uncredited_deposit_update_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="account",
            name="user_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="common.online_user",
            ),
        ),
        migrations.AddField(
            model_name="online_user",
            name="is_blacklisted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="online_user",
            name="is_frozen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="online_user",
            name="is_lost",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="online_user",
            name="password",
            field=models.CharField(default="666666", max_length=20),
        ),
        migrations.AddField(
            model_name="online_user",
            name="phone_num",
            field=models.CharField(default="10086", max_length=20),
        ),
        migrations.AddField(
            model_name="online_user",
            name="user_name",
            field=models.CharField(default="Unknown", max_length=20),
        ),
        migrations.AlterField(
            model_name="account",
            name="identity_card",
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_lost",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="creditcardexaminer",
            name="account",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="creditcardexaminer",
            name="password",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="online_user",
            name="identity_card",
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.CreateModel(
            name="online_bank_manager",
            fields=[
                (
                    "online_bank_manager_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("account", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=20)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlackList",
            fields=[
                ("list_id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.online_user",
                    ),
                ),
                (
                    "online_bank_manager_id",
                    models.ForeignKey(
                        db_column="online_bank_manager_id",
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.online_bank_manager",
                    ),
                ),
            ],
        ),
    ]
