# Generated by Django 5.0.6 on 2024-06-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_account_phone_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrepayment',
            name='is_overdue',
        ),
        migrations.AddField(
            model_name='loanrecord',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
    ]
