# Generated by Django 5.0.6 on 2024-06-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_loanrepayment_is_overdue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer_record',
            name='cashier_id',
            field=models.IntegerField(null=True),
        ),
    ]
