# Generated by Django 5.0.6 on 2024-06-10 07:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_loanapplication_loandepartmentmanager_lender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='open_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CreditCardExaminer',
            fields=[
                ('credit_examiner_id', models.AutoField(primary_key=True, serialize=False)),
                ('check_authority', models.BooleanField(default=False)),
                ('account', models.CharField(default='000000', max_length=30)),
                ('password', models.CharField(default='password', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardApplication',
            fields=[
                ('apply_id', models.AutoField(primary_key=True, serialize=False)),
                ('apply_status', models.BooleanField(default=False)),
                ('apply_result', models.BooleanField(default=False)),
                ('apply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('have_open', models.BooleanField(default=False)),
                ('online_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.online_user')),
                ('creditCardExaminer', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.creditcardexaminer')),
            ],
        ),
    ]
