# Generated by Django 5.0.6 on 2024-06-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counteropt', '0002_remove_account_identity_card_remove_cashier_employee_and_more'),
        ('foreign_exchange', '0002_alter_currencyholding_online_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='account',
        ),
        migrations.DeleteModel(
            name='online_user',
        ),
        migrations.DeleteModel(
            name='cashier',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='sys_manage',
        ),
    ]
